default: &base
  user: git
  listen: 0.0.0.0:22
  http_listen: 0.0.0.0:8080
  deadline: 3600
  idle_timeout: 180
  git_path: /usr/bin/git
  git_repo_dir: /data/repositories # repos base dir
  db_url: postgresql://growerlab:growerlab@127.0.0.1:5432/growerlab?sslmode=disable
  redis:
    host: 127.0.0.1
    port: 6379
    max_idle: 5
    max_active: 512
    idle_timeout: 120
    namespace: "master:mensa"
    permission_namespace: "master"

production:
  <<: *base

dev:
  <<: *base
  user: moli
  listen: 0.0.0.0:8022
  http_listen: 0.0.0.0:8080
  git_repo_dir: test/repos
  host_keys: []
