default: &base
  user: git
  listen: 0.0.0.0:22
  http_listen: 0.0.0.0:8080
  host_keys:
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_ecdsa_key
  deadline: 3600
  idle_timeout: 180
  git_path: /usr/bin/git

production:
  <<: *base

dev:
  <<: *base
  user: moli
  listen: 0.0.0.0:8022
  http_listen: 0.0.0.0:8080
